version: "3.7"

services:
    gateway-envoy:
        build:
            context: ./config
            dockerfile: Dockerfile-gateway
        ports:
            - "10000:10000"
            - "8091:8091"
            - "8080:8080"
            - "8001:8001"
