version: '3'

volumes:
  postgres_data_keycloak:
  config_data_keycloak:

services:
  postgres:
    container_name: keycloak-postgres
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_keycloak:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always

  keycloak:
    image: jboss/keycloak:${KEYCLOAK_VERSION}
    container_name: keycloak
    environment:
      DB_VENDOR: ${KEYCLOAK_DB_VENTOR}
      DB_ADDR: ${KEYCLOAK_DB_ADDR}
      DB_DATABASE: ${KEYCLOAK_DB_DATABASE}
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_SCHEMA: ${KEYCLOAK_DB_SCHEMA}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      PROXY_ADDRESS_FORWARDING: ${KEYCLOAK_PROXY_ADDRESS_FORWARDING}
    ports:
      - ${KEYCLOAK_PORT}:8080
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - config_data_keycloak:/var/lib/keycloak/data
