version: '3.9'

volumes:
  postgres_data_keycloak:
  config_data_keycloak:

services:
  postgres:
    container_name: keycloak-postgres
    image: postgres:12
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: admin@database
    volumes:
      - postgres_data_keycloak:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: always

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: admin@database
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin@keycloak
      KEYCLOAK_USER: user
      KEYCLOAK_PASSWORD: user@keycloak
      PROXY_ADDRESS_FORWARDING: true
    ports:
      - 8080:8080
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - config_data_keycloak:/var/lib/keycloak/data
