const BACKEND_UNIVERSAL_ERROR_CODE: number = 1;
const BACKEND_UNIVERSAL_ERROR_MSG: string = "Something went wrong from the backend";

const BACKEND_UNIVERSAL_SUCCESS_CODE: number = 0;
const NOT_FOUND_CODE: number = 2;

const SAVED_OVERLIMIT_FILE_SIZE_CODE: number = 2;
const SAVED_INVALID_EXTENSIONS_FILE_CODE: number = 3;

export {
    BACKEND_UNIVERSAL_SUCCESS_CODE,
    NOT_FOUND_CODE,

    BACKEND_UNIVERSAL_ERROR_CODE,
    BACKEND_UNIVERSAL_ERROR_MSG,

    SAVED_OVERLIMIT_FILE_SIZE_CODE,
    SAVED_INVALID_EXTENSIONS_FILE_CODE,
}