name: capstone-be CD

on:
  push:
    branches: [ "be-production" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
     APP_PORT_1: ${{ secrets.APP_PORT_1 }}
     DB_PORT: ${{ secrets.DB_PORT }}
     DB_HOST: ${{ secrets.DB_HOST }}
     DB_USER: ${{ secrets.DB_USER }}
     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
     DB_NAME: ${{ secrets.DB_NAME }}  
     DB_CONNECTION_LIMIT: ${{ secrets.DB_CONNECTION_LIMIT }}
    defaults:
      run:
        working-directory: ./software-capstone-be
    steps:
    - name: Connect to server
      uses: appleboy/ssh-action@master 
      with:
        host: ${{ secrets.HOST }}
        key: ${{ secrets.SSH_KEY }}
        username: ${{ secrets.USER_NAME }}
        envs: FOO,BAR,SHA
        command_timeout: 20m
        script_stop: true
        script: |
         cd software-capstone
         git checkout be-production
         git pull
         cd software-capstone-be
         sudo docker build --platform linux/amd64 -t namphamhcmus1906/capstone:be.production . 
         cd -
         sudo docker stop be_nodejs_production || true 
         sudo docker rm be_nodejs_production || true
         sudo docker run -m=4g -t -d -p ${{ secrets.APP_PORT_1 }}:${{ secrets.APP_PORT_1 }} --name be_nodejs_production --env APP_PORT=8080 --env DB_PORT=3306 --env DB_HOST=api.ieltswarrior.me --env DB_USER=root --env DB_PASSWORD=xecnyw-xevbiK-gazsi6 --env DB_NAME=warrior --env DB_CONNECTION_LIMIT=10 namphamhcmus1906/capstone:be.production
   
